ALTER TABLE kanban_boards
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE sprint_tasks
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE sprints
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE task_comments
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE task_progresses
    MODIFY id INT AUTO_INCREMENT;

ALTER TABLE task_statuses
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE task_subscribers
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE tasks
    MODIFY id INT AUTO_INCREMENT;