# -------------------
# 1. Builder stage
# -------------------
FROM maven:3.9-eclipse-temurin-23 AS builder
WORKDIR /app

COPY pom.xml ./pom.xml
COPY core/pom.xml ./core/pom.xml
COPY infrastructure/pom.xml ./infrastructure/pom.xml
COPY mail-service/pom.xml ./mail-service/pom.xml
COPY core/notifier.pom.xml ./notifier/pom.xml

RUN mvn dependency:go-offline -B

COPY . ./
RUN rm -rf ./notifier
COPY core/notifier.pom.xml ./notifier/pom.xml

ARG SENTRY_ORG
ARG SENTRY_PROJECT

RUN --mount=type=secret,id=sentry_token export SENTRY_AUTH_TOKEN=$(cat /run/secrets/sentry_token) && SENTRY_ORG=${SENTRY_ORG} SENTRY_PROJECT=${SENTRY_PROJECT} mvn clean package -DskipTests -B

FROM bellsoft/liberica-runtime-container:jre-23-slim-musl AS runtime
WORKDIR /app

COPY --from=builder /app/core/target/core-*.jar app.jar

EXPOSE 8080

RUN addgroup --system appgroup && adduser --system appuser --ingroup appgroup
USER appuser

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
